// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://rdbhjamuqusrfzrjvrfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkYmhqYW11cXVzcmZ6cmp2cmZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUwNjI0NDQsImV4cCI6MjEwMDYzODQ0NH0.ELJfXwxLwmGU-kR32lAA5lD8yX7xlFBhG57A_afTXP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: Database types are empty (Cloud disconnected / external Supabase project pending).
// We cast to a loosely-typed client so app code can query tables defined in the external schema.
export const supabase: SupabaseClient<any, "public", any> = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
